name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.*'

      - name: Define cache paths
        id: cache_paths
        run: |
          echo "::set-output name=mod::$(go env GOMODCACHE)"
          echo "::set-output name=build::$(go env GOCACHE)"

      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache_paths.outputs.mod }}
            ${{ steps.cache_paths.outputs.build }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
