name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.*'
        run: |
          echo $GOPATH
          echo $GOCACHE

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
